### ISSUE TITLE
请问下容器管理页面的端口是多少

### ISSUE THREAD

**Issue by liukaips** [guojiaxing1995/easy-test#11]

**Comment by guojiaxing1995** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        你是说 docker-manager 里面的容器管理吧。这个页面的端口就是登陆页面的端口，你部署的时候可以进行指定
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                302802003
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年6月7日 ***@***.***> 写道： 





—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
