### ISSUE TITLE
点击测试执行模块提示 Error: Cannot find module './views/execute/ExecuteTest.vue'

### ISSUE THREAD

**Issue by gglo** [guojiaxing1995/easy-test#13]
![image](https://user-images.githubusercontent.com/22768621/131253291-a302c5b8-fcfb-4f2f-84be-bd2c70183742.png)

**Comment by gglo** [comment]
![image](https://user-images.githubusercontent.com/22768621/131254362-8c5a9fd5-6cfc-4922-9ce5-dd8a54e94914.png)

**Comment by guojiaxing1995** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    node 什么版本的启动命令是怎么执行的
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                302802003
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年8月29日 ***@***.***> 写道： 





—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mszi** [comment]
请问该怎么不部署啊，教程有点不太懂，谢谢大佬解答🙏

**Comment by guojiaxing1995** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    部署的有问题
        需要提前储备 docker docker-compose nginx 等相关知识
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                302802003
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年11月8日 ***@***.***> 写道： 




请问该怎么不部署啊，教程有点不太懂，谢谢大佬解答🙏



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mszi** [comment]
😂好嘛，谢谢大佬

**Comment by CCodeInspect** [comment]
> 😂好嘛，谢谢大佬

hello，后端项目部署包有点问题，可以帮忙看下嘛。
