### ISSUE TITLE
ImportError: No module named libs.init

### ISSUE THREAD

**Issue by CCodeInspect** [guojiaxing1995/easy-test#36]
【1】我在服务器上部署后端代码的时候报"ImportError: No module named libs.init"，然后我在starter.py中加上了“sys.path.append('/home/lighthouse/item/easy-test/easy-test-flask/app')”这样一段，运行starter.py还是报“No module named libs.init”。

![image](https://user-images.githubusercontent.com/44918169/196039425-d243cc21-23cf-4bae-9d3f-0aba18dbf5b5.png)

![image](https://user-images.githubusercontent.com/44918169/196039452-8f3d72ce-6da6-4fe0-828f-2ebceb278df7.png)

【2】我在本地部署后端代码的时候，lib.init可以被找到，但是如下目录找不到：flask_mail / flask_apscheduler / flask_celery /flask_pymongo / flask_socketio ，请问这几个目录是自定义的目录吗？

<img width="844" alt="image" src="https://user-images.githubusercontent.com/44918169/196039479-aa85abdf-28c3-4402-b1d6-8c0aa3becfa0.png">

**Comment by guojiaxing1995** [comment]
需要提供详细步骤

从 Windows 版邮件发送

发件人: pauline_lee
发送时间: 2022年10月16日 21:59
收件人: guojiaxing1995/easy-test
抄送: Subscribed
主题: [guojiaxing1995/easy-test] ImportError: No module named libs.init(Issue #36)

【1】我在服务器上部署后端代码的时候报"ImportError: No module named libs.init"，然后我在starter.py中加上了“sys.path.append('/home/lighthouse/item/easy-test/easy-test-flask/app')”这样一段，运行starter.py还是报“No module named libs.init”。


【2】我在本地部署后端代码的时候，lib.init可以被找到，但是如下目录找不到：flask_mail / flask_apscheduler / flask_celery /flask_pymongo / flask_socketio ，请问这几个目录是自定义的目录吗？

**Comment by CCodeInspect** [comment]
1.我突然明白了，我在服务器使用python2的解释器运行starter.py，本地是python3的解释器，所以服务器上的部署会报"ImportError: No module named libs.init"，改用python3的解释器可以找到lib.init。感谢您的回复😄。

![image](https://user-images.githubusercontent.com/44918169/196072025-e674fc92-f477-4eeb-8f65-794e32aace20.png)
![image](https://user-images.githubusercontent.com/44918169/196072035-09f4aad8-0d7f-408c-9d1c-b3d02e7c1fd1.png)

**Comment by CCodeInspect** [comment]
大佬，又执行不下去了，报
<img width="924" alt="image" src="https://user-images.githubusercontent.com/44918169/196084061-0a6196a6-dfc3-426b-9f16-ae9e64de2e8c.png">

**Comment by llaichiyu** [comment]
flask_celery.py是site-packages下的第三方的包啊，为啥会报错啊🤔️
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/44918169/196086311-b6444d55-cfc8-488b-843f-570e61ec1b2e.png">

**Comment by CCodeInspect** [comment]
flask_celery.py是site-packeages下的第三方的包啊，为啥会报错啊🤔️


<img width="1493" alt="image" src="https://user-images.githubusercontent.com/44918169/196086349-6705b3c0-219a-45fb-9eb2-cc87cff4d391.png">
