### ISSUE TITLE
本地有mysql数据库，还需要MongoDB吗？

### ISSUE THREAD

**Issue by zuokexia** [guojiaxing1995/easy-test#5]
运行starter.py的时候会报错
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:8090: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

**Comment by guojiaxing1995** [comment]
需要mongodb，mongodb存了用例执行记录日志、用例修改记录和定时任务的数据
