### ISSUE TITLE
用例多步骤执行

### ISSUE THREAD

**Issue by liukaips** [guojiaxing1995/easy-test#8]
一个工程下多工用例怎么关联执行呢

**Comment by guojiaxing1995** [comment]
工程配置模块可以拖动用例进行配置和排序，配置里的排序就是执行顺序，可以通过后置处理将接口返回保存，然后再下一个接口的入参里添加环境变量
具体可以看一下  https://blog.csdn.net/qq_36450484/article/details/107332571?spm=1001.2014.3001.5501
